CREATE TABLE IF NOT EXISTS APM_BUSINESS_OWNER(
  OWNER_ID INTEGER  AUTO_INCREMENT,
  OWNER_NAME VARCHAR(200) NOT NULL,
  OWNER_EMAIL VARCHAR(300) NOT NULL,
  OWNER_DESC VARCHAR(1500),
  OWNER_SITE VARCHAR(200),
  TENANT_ID INTEGER,
  PRIMARY KEY(OWNER_ID),
  UNIQUE (OWNER_NAME,OWNER_EMAIL,TENANT_ID)
);

CREATE TABLE IF NOT EXISTS APM_BUSINESS_OWNER_PROPERTY(
  OWNER_PROP_ID INTEGER AUTO_INCREMENT,
  OWNER_ID INTEGER NOT NULL,
  NAME VARCHAR(200) NOT NULL,
  VALUE VARCHAR(300) NOT NULL,
  SHOW_IN_STORE BOOLEAN NOT NULL,
  PRIMARY KEY(OWNER_PROP_ID),
  FOREIGN KEY(OWNER_ID) REFERENCES APM_BUSINESS_OWNER(OWNER_ID)
);

ALTER TABLE APM_APP ADD VISIBLE_ROLES varchar(500);

UPDATE APM_APP_JAVA_POLICY SET FULL_QUALIFI_NAME = 'org.wso2.carbon.appmgt.gateway.handlers.security.authentication.SAML2AuthenticationHandler' WHERE FULL_QUALIFI_NAME = 'SAML2 Authentication Handler';

INSERT INTO APM_APP_JAVA_POLICY(DISPLAY_NAME, FULL_QUALIFI_NAME, DESCRIPTION, DISPLAY_ORDER_SEQ_NO,IS_MANDATORY,IS_GLOBAL)
VALUES ('Subscription Handler', 'org.wso2.carbon.appmgt.gateway.handlers.subscription.SubscriptionsHandler', '', 3,TRUE,TRUE);

INSERT INTO APM_APP_JAVA_POLICY(DISPLAY_NAME, FULL_QUALIFI_NAME, DESCRIPTION, DISPLAY_ORDER_SEQ_NO,IS_MANDATORY,IS_GLOBAL)
VALUES ('Authorization Handler', 'org.wso2.carbon.appmgt.gateway.handlers.security.entitlement.AuthorizationHandler','',4,TRUE,TRUE);

UPDATE APM_APP_JAVA_POLICY SET DISPLAY_ORDER_SEQ_NO = '5' WHERE DISPLAY_NAME = 'Entitlement Handler';

UPDATE APM_APP_JAVA_POLICY SET DISPLAY_ORDER_SEQ_NO = '6' WHERE DISPLAY_NAME = 'API Throttle Handler';

UPDATE APM_APP_JAVA_POLICY SET DISPLAY_ORDER_SEQ_NO = '7' WHERE DISPLAY_NAME = 'Publish Statistics:';
